# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.5

# GNOME 51 mirror ahead of ::gentoo; drop each tag below when ::gentoo reaches this version
# BENTOO-DIVERGENCE: LICENSE - crate LICENSE+= regenerated by pycargoebuild from the 51.0 Cargo.lock
# BENTOO-DIVERGENCE: DEPEND - 51.0 meson.build no longer uses lcms2
# BENTOO-DIVERGENCE: RDEPEND - 51.0 meson.build no longer uses lcms2

EAPI=8

CRATES="
	adler2@2.0.1
	aho-corasick@1.1.5
	aliasable@0.1.3
	anyhow@1.0.104
	arc-swap@1.9.2
	ashpd@0.13.13
	async-broadcast@0.7.2
	async-channel@2.5.0
	async-executor@1.14.0
	async-fs@2.2.0
	async-global-executor@3.1.0
	async-io@2.6.0
	async-lock@3.4.2
	async-process@2.5.0
	async-recursion@1.1.1
	async-signal@0.2.14
	async-task@4.7.1
	async-trait@0.1.92
	atomic-waker@1.1.2
	autocfg@1.5.1
	bit_field@0.10.3
	bitflags@1.3.2
	bitflags@2.13.1
	block@0.1.6
	blocking@1.7.0
	bumpalo@3.20.3
	bytemuck@1.25.2
	byteorder-lite@0.1.0
	cairo-rs@0.22.0
	cairo-sys-rs@0.22.0
	cc@1.4.4
	cfg-expr@0.20.9
	cfg-if@1.0.4
	cfg_aliases@0.2.2
	chrono@0.4.45
	color_quant@1.1.0
	concurrent-queue@2.5.0
	crc32fast@1.5.1
	crossbeam-deque@0.8.7
	crossbeam-epoch@0.9.20
	crossbeam-utils@0.8.22
	crunchy@0.2.4
	defmt-macros@1.1.1
	defmt-parser@1.0.0
	defmt@1.1.1
	dlib@0.5.3
	either@1.18.0
	encoding_rs@0.8.35
	endi@1.1.1
	enumflags2@0.7.12
	enumflags2_derive@0.7.12
	env_filter@2.0.0
	env_logger@0.11.11
	equivalent@1.0.2
	errno@0.3.14
	event-listener-strategy@0.5.4
	event-listener@5.4.2
	exr@1.74.2
	fastrand@2.5.0
	fax@0.2.7
	fdeflate@0.3.7
	fearless_simd@0.4.1
	field-offset@0.3.6
	find-msvc-tools@0.1.11
	flate2@1.1.9
	futures-channel@0.3.34
	futures-core@0.3.34
	futures-executor@0.3.34
	futures-io@0.3.34
	futures-lite@2.6.1
	futures-macro@0.3.34
	futures-sink@0.3.34
	futures-task@0.3.34
	futures-timer@3.0.4
	futures-util@0.3.34
	gdk-pixbuf-sys@0.22.0
	gdk-pixbuf@0.22.0
	gdk4-sys@0.11.4
	gdk4-wayland-sys@0.11.0
	gdk4-wayland@0.11.4
	gdk4-x11-sys@0.11.0
	gdk4-x11@0.11.4
	gdk4@0.11.4
	getrandom@0.4.3
	gettext-rs@0.8.0
	gettext-sys@0.27.0
	gif@0.14.2
	gio-sys@0.22.8
	gio-unix-sys@0.22.0
	gio-unix@0.22.8
	gio@0.22.8
	glib-macros@0.22.6
	glib-sys@0.22.8
	glib@0.22.8
	glycin-builtin@4.0.0
	glycin-common@2.0.0
	glycin-core@4.0.0
	glycin-external@4.0.0
	glycin-image-rs@2.2.0
	glycin-utils@5.0.0
	glycin@4.0.0
	gobject-sys@0.22.6
	graphene-rs@0.22.8
	graphene-sys@0.22.8
	gsk4-sys@0.11.4
	gsk4@0.11.4
	gtk4-macros@0.11.4
	gtk4-sys@0.11.4
	gtk4@0.11.4
	gufo-common@2.0.0
	gufo-exif@0.5.0
	gufo-jpeg@0.5.1
	gufo-png@0.5.0
	gufo-tiff@0.5.0
	gufo-webp@0.5.0
	gufo-xmp@0.5.0
	gufo@0.5.0
	gvdb-macros@0.1.16
	gvdb@0.10.0
	gweather-sys@4.8.0
	half@2.7.1
	hashbrown@0.17.1
	hayro-jpeg2000@0.3.5
	heck@0.4.1
	heck@0.5.0
	hermit-abi@0.5.2
	hex@0.4.3
	image-extras@0.1.1
	image-webp@0.2.4
	image@0.25.10
	indexmap@2.14.0
	itoa@1.0.18
	jiff-core@0.1.0
	jiff-static@0.2.35
	jiff@0.2.35
	jpeg-encoder@0.7.1
	js-sys@0.3.104
	lazy_static@1.5.0
	lebe@0.5.3
	libadwaita-sys@0.9.2
	libadwaita@0.9.2
	libc@0.2.189
	libgweather@4.8.0
	libloading@0.8.9
	libm@0.2.16
	libseccomp-sys@0.3.0
	libseccomp@0.4.0
	linux-raw-sys@0.12.1
	litrs@1.0.0
	locale_config@0.3.0
	log@0.4.34
	malloc_buf@0.0.6
	matchers@0.2.0
	memchr@2.8.3
	memmap2@0.9.11
	memoffset@0.9.1
	miniz_oxide@0.8.9
	miniz_oxide@0.9.1
	moxcms@0.8.1
	nix@0.31.3
	nu-ansi-term@0.50.3
	num-complex@0.4.6
	num-traits@0.2.19
	objc-foundation@0.1.1
	objc@0.2.7
	objc_id@0.1.1
	once_cell@1.21.4
	ordered-stream@0.2.0
	ouroboros@0.18.5
	ouroboros_macro@0.18.5
	pango-sys@0.22.0
	pango@0.22.8
	parking@2.2.1
	paste@1.0.15
	pin-project-lite@0.2.17
	piper@0.2.5
	pkg-config@0.3.34
	png@0.18.1
	polling@3.11.0
	portable-atomic-util@0.2.7
	portable-atomic@1.15.0
	proc-macro-crate@3.5.0
	proc-macro2-diagnostics@0.10.1
	proc-macro2@1.0.107
	pulp-wasm-simd-flag@0.1.1
	pulp@0.22.3
	pxfm@0.1.30
	qoi@0.4.1
	quick-error@2.0.1
	quick-xml@0.39.4
	quote@1.0.47
	r-efi@6.0.0
	raw-cpuid@11.6.0
	rayon-core@1.13.0
	rayon@1.12.0
	reborrow@0.5.5
	regex-automata@0.4.18
	regex-syntax@0.8.11
	regex@1.13.1
	rmp-serde@1.3.1
	rmp@0.8.15
	rustc_version@0.4.1
	rustix@1.1.4
	rustversion@1.0.23
	same-file@1.0.6
	semver@1.0.28
	serde@1.0.229
	serde_core@1.0.229
	serde_derive@1.0.229
	serde_json@1.0.151
	serde_repr@0.1.21
	serde_spanned@1.1.1
	sharded-slab@0.1.7
	shlex@2.0.1
	signal-hook-registry@1.4.8
	simd-adler32@0.3.10
	slab@0.4.12
	smallvec@1.15.2
	static_assertions@1.1.0
	strum@0.28.0
	strum_macros@0.28.0
	syn@2.0.119
	syn@3.0.4
	system-deps@7.0.8
	target-lexicon@0.13.5
	temp-dir@0.1.16
	tempfile@3.27.0
	thiserror-impl@2.0.20
	thiserror@2.0.20
	thread_local@1.1.10
	tiff@0.11.3
	toml@1.1.4+spec-1.1.0
	toml_datetime@1.1.1+spec-1.1.0
	toml_edit@0.25.13+spec-1.1.0
	toml_parser@1.1.3+spec-1.1.0
	toml_writer@1.1.2+spec-1.1.0
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing-subscriber@0.3.23
	tracing@0.1.44
	uds_windows@1.2.1
	unicode-ident@1.0.24
	uuid@1.25.0
	version-compare@0.2.1
	version_check@0.9.5
	walkdir@2.5.0
	wasm-bindgen-macro-support@0.2.127
	wasm-bindgen-macro@0.2.127
	wasm-bindgen-shared@0.2.127
	wasm-bindgen@0.2.127
	weezl@0.1.12
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.11
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-link@0.2.1
	windows-sys@0.61.2
	winnow@1.0.4
	x11-dl@2.21.0
	xml@1.4.0
	yansi@1.0.1
	yeslogic-fontconfig-sys@6.0.1
	zbus@5.19.0
	zbus_macros@5.19.0
	zbus_names@4.3.4
	zcheapstr@1.1.0
	zerocopy-derive@0.8.56
	zerocopy@0.8.56
	zmij@1.0.23
	zune-core@0.5.3
	zune-inflate@0.2.54
	zune-jpeg@0.5.15
	zvariant@5.15.0
	zvariant_derive@5.15.0
	zvariant_utils@4.2.0
"

RUST_MIN_VER="1.93"

inherit cargo gnome.org gnome2 meson xdg

DESCRIPTION="View images"
HOMEPAGE="https://apps.gnome.org/Loupe"

# SRC_URI for loupe is set by gnome.org eclass.
SRC_URI+=" ${CARGO_CRATE_URIS}"

LICENSE="GPL-3+"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD IJG ISC MIT
	Unicode-3.0
	|| ( LGPL-2.1+ MPL-2.0 )
"
SLOT="0"
KEYWORDS="~amd64"

IUSE="X heif gif jpeg jpegxl svg tiff"

BDEPEND="
	dev-util/itstool
	virtual/pkgconfig
"
# sys-crates in pycargoebuild order
DEPEND="
	x11-libs/cairo[X?]
	>x11-libs/gdk-pixbuf-2.42.10-r1[gif?,jpeg?,tiff?]
	dev-libs/glib:2
	sys-devel/gettext
	media-libs/graphene
	x11-libs/pango[X?]
	media-libs/fontconfig
"
# meson.build file
DEPEND+="
	>=gui-libs/gtk-4.16.0:4[X?,wayland]
	>=gui-libs/libadwaita-1.8.0:1
	>=dev-libs/libgweather-4.0.0:4=
	>=sys-libs/libseccomp-2.5.0
"
RDEPEND="${DEPEND}
	media-libs/glycin-loaders:2=[heif?,jpegxl?,svg?]
"

QA_FLAGS_IGNORED="usr/bin/loupe"

src_configure() {
	local emesonargs=(
		$(meson_feature X x11)
	)
	meson_src_configure
	ln -s "${CARGO_HOME}" "${BUILD_DIR}/cargo-home" || die
}

pkg_preinst() {
	xdg_pkg_preinst
}

pkg_postinst() {
	xdg_pkg_postinst
	gnome2_schemas_update
}

pkg_postrm() {
	xdg_pkg_postrm
	gnome2_schemas_update
}
