# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.17.1

EAPI=8

CRATES="
	anyhow@1.0.102
	atomic-waker@1.1.2
	autocfg@1.5.0
	base64@0.22.1
	bitflags@2.11.1
	block-buffer@0.12.0
	bumpalo@3.20.2
	bytes@1.11.1
	cairo-rs@0.22.0
	cairo-sys-rs@0.22.0
	caseless@0.2.2
	cc@1.2.62
	cfg-expr@0.20.7
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	comrak@0.52.0
	const-oid@0.10.2
	cpufeatures@0.3.0
	crypto-common@0.2.1
	deranged@0.5.8
	digest@0.11.3
	displaydoc@0.2.5
	entities@1.0.1
	equivalent@1.0.2
	fallible-iterator@0.3.0
	fallible-streaming-iterator@0.1.9
	fastrand@2.4.1
	field-offset@0.3.6
	filetime@0.2.29
	find-msvc-tools@0.1.9
	finl_unicode@1.4.0
	foldhash@0.1.5
	form_urlencoded@1.2.2
	futures-channel@0.3.32
	futures-core@0.3.32
	futures-executor@0.3.32
	futures-io@0.3.32
	futures-macro@0.3.32
	futures-sink@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	gdk-pixbuf-sys@0.22.0
	gdk-pixbuf@0.22.0
	gdk4-sys@0.11.2
	gdk4@0.11.2
	getrandom@0.2.17
	getrandom@0.3.4
	getrandom@0.4.2
	gio-sys@0.22.0
	gio@0.22.6
	glib-macros@0.22.6
	glib-sys@0.22.6
	glib@0.22.7
	gobject-sys@0.22.6
	graphene-rs@0.22.0
	graphene-sys@0.22.0
	gsk4-sys@0.11.1
	gsk4@0.11.1
	gtk4-macros@0.11.0
	gtk4-sys@0.11.3
	gtk4@0.11.3
	hashbrown@0.15.5
	hashbrown@0.17.1
	hashlink@0.10.0
	heck@0.5.0
	http-body-util@0.1.3
	http-body@1.0.1
	http@1.4.0
	httparse@1.10.1
	hybrid-array@0.4.12
	hyper-rustls@0.27.9
	hyper-util@0.1.20
	hyper@1.9.0
	icu_collections@2.2.0
	icu_locale_core@2.2.0
	icu_normalizer@2.2.0
	icu_normalizer_data@2.2.0
	icu_properties@2.2.0
	icu_properties_data@2.2.0
	icu_provider@2.2.0
	id-arena@2.3.0
	idna@1.1.0
	idna_adapter@1.2.2
	indexmap@2.14.0
	ipnet@2.12.0
	itoa@1.0.18
	jetscii@0.5.3
	jobserver@0.1.34
	js-sys@0.3.98
	latex-rust@1.0.4
	leb128fmt@0.1.0
	libadwaita-sys@0.9.1
	libadwaita@0.9.1
	libc@0.2.186
	libsqlite3-sys@0.35.0
	litemap@0.8.2
	log@0.4.29
	lru-slab@0.1.2
	memchr@2.8.0
	memoffset@0.9.1
	mio@1.2.0
	num-conv@0.2.1
	once_cell@1.21.4
	pango-sys@0.22.0
	pango@0.22.6
	percent-encoding@2.3.2
	phf@0.13.1
	phf_codegen@0.13.1
	phf_generator@0.13.1
	phf_shared@0.13.1
	pin-project-lite@0.2.17
	pkg-config@0.3.33
	potential_utf@0.1.5
	powerfmt@0.2.0
	ppv-lite86@0.2.21
	prettyplease@0.2.37
	proc-macro-crate@3.5.0
	proc-macro2@1.0.106
	quinn-proto@0.11.14
	quinn-udp@0.5.14
	quinn@0.11.9
	quote@1.0.45
	r-efi@5.3.0
	r-efi@6.0.0
	rand@0.9.4
	rand_chacha@0.9.0
	rand_core@0.9.5
	reqwest@0.12.28
	ring@0.17.14
	rusqlite@0.37.0
	rustc-hash@2.1.2
	rustc_version@0.4.1
	rustls-pki-types@1.14.1
	rustls-webpki@0.103.13
	rustls@0.23.40
	rustversion@1.0.22
	ryu@1.0.23
	semver@1.0.28
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.149
	serde_spanned@1.1.1
	serde_urlencoded@0.7.1
	sha2@0.11.0
	shlex@1.3.0
	siphasher@1.0.3
	slab@0.4.12
	smallvec@1.15.1
	socket2@0.6.3
	sourceview5-sys@0.11.0
	sourceview5@0.11.0
	stable_deref_trait@1.2.1
	subtle@2.6.1
	syn@2.0.117
	sync_wrapper@1.0.2
	synstructure@0.13.2
	system-deps@7.0.8
	tar@0.4.46
	target-lexicon@0.13.3
	thiserror-impl@2.0.18
	thiserror@2.0.18
	time-core@0.1.8
	time-macros@0.2.27
	time@0.3.47
	tinystr@0.8.3
	tinyvec@1.11.0
	tinyvec_macros@0.1.1
	tokio-macros@2.7.0
	tokio-rustls@0.26.4
	tokio-util@0.7.18
	tokio@1.52.3
	toml@1.1.2+spec-1.1.0
	toml_datetime@1.1.1+spec-1.1.0
	toml_edit@0.25.11+spec-1.1.0
	toml_parser@1.1.2+spec-1.1.0
	toml_writer@1.1.1+spec-1.1.0
	tower-http@0.6.10
	tower-layer@0.3.3
	tower-service@0.3.3
	tower@0.5.3
	tracing-core@0.1.36
	tracing@0.1.44
	try-lock@0.2.5
	ttf-parser@0.25.1
	typed-arena@2.0.2
	typenum@1.20.0
	unicode-ident@1.0.24
	unicode-normalization@0.1.25
	unicode-xid@0.2.6
	untrusted@0.9.0
	url@2.5.8
	utf8_iter@1.0.4
	uuid@1.23.1
	vcpkg@0.2.15
	version-compare@0.2.1
	want@0.3.1
	wasi@0.11.1+wasi-snapshot-preview1
	wasip2@1.0.3+wasi-0.2.9
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-bindgen-futures@0.4.71
	wasm-bindgen-macro-support@0.2.121
	wasm-bindgen-macro@0.2.121
	wasm-bindgen-shared@0.2.121
	wasm-bindgen@0.2.121
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasm-streams@0.4.2
	wasmparser@0.244.0
	web-sys@0.3.98
	web-time@1.1.0
	webpki-roots@1.0.7
	windows-link@0.2.1
	windows-sys@0.52.0
	windows-sys@0.60.2
	windows-sys@0.61.2
	windows-targets@0.52.6
	windows-targets@0.53.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_gnullvm@0.53.1
	windows_aarch64_msvc@0.52.6
	windows_aarch64_msvc@0.53.1
	windows_i686_gnu@0.52.6
	windows_i686_gnu@0.53.1
	windows_i686_gnullvm@0.52.6
	windows_i686_gnullvm@0.53.1
	windows_i686_msvc@0.52.6
	windows_i686_msvc@0.53.1
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnu@0.53.1
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_gnullvm@0.53.1
	windows_x86_64_msvc@0.52.6
	windows_x86_64_msvc@0.53.1
	winnow@1.0.2
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-bindgen@0.57.1
	wit-component@0.244.0
	wit-parser@0.244.0
	writeable@0.6.3
	yoke-derive@0.8.2
	yoke@0.8.2
	zerocopy-derive@0.8.48
	zerocopy@0.8.48
	zerofrom-derive@0.1.7
	zerofrom@0.1.7
	zeroize@1.8.2
	zerotrie@0.2.4
	zerovec-derive@0.11.3
	zerovec@0.11.6
	zmij@1.0.21
	zstd-safe@7.2.4
	zstd-sys@2.0.16+zstd.1.5.7
	zstd@0.13.3
"

RUST_MIN_VER="1.92.0"

inherit cargo gnome2-utils meson xdg

DESCRIPTION="GTK/libadwaita chat client for local and remote Ollama servers"
HOMEPAGE="https://github.com/moooossee/moose"
SRC_URI="
	https://github.com/moooossee/moose/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="GPL-3+"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 BSD
	CDLA-Permissive-2.0 ISC MIT Unicode-3.0 Unicode-DFS-2016 ZLIB
"
# STIX Two Math font, embedded into the binary by the latex-rust crate
LICENSE+=" OFL-1.1"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

# sys-crates in Cargo.lock: cairo, gdk-pixbuf, gdk4/gsk4/gtk4, gio/glib/gobject,
# graphene, libadwaita, sqlite (system, FTS5 is always on in ::gentoo), pango,
# gtksourceview, zstd (forced to pkg-config in src_compile).
# gtk4 is built with feature gnome_50 (v4_22), libadwaita with v1_9.
DEPEND="
	app-arch/zstd:=
	dev-db/sqlite:3
	dev-libs/glib:2
	>=gui-libs/gtk-4.22:4
	>=gui-libs/libadwaita-1.9:1
	gui-libs/gtksourceview:5
	media-libs/graphene
	x11-libs/cairo
	x11-libs/gdk-pixbuf:2
	x11-libs/pango
"
# pdftotext is spawned at runtime to import PDF attachments
RDEPEND="
	${DEPEND}
	app-text/poppler[utils]
"
BDEPEND="
	dev-libs/glib:2
	virtual/pkgconfig
"

src_configure() {
	local emesonargs=(
		# The non-gui binary is an empty "fn main() {}" in 0.5.0, and the
		# desktop file, D-Bus service and schema meson installs all point at
		# the GUI, so gui=false would ship a no-op program.
		-Dgui=true
		-Dcargo_profile=$(usex debug dev release)
	)
	meson_src_configure
}

src_compile() {
	# build-aux/cargo-build.py runs cargo itself; cargo_env gives it the
	# eclass toolchain and flags. CARGO_HOME (offline, vendored) is already
	# exported by cargo_gen_config.
	local -x ZSTD_SYS_USE_PKG_CONFIG=1
	# Panic locations embed the vendored crate paths under ${WORKDIR}.
	# Not "local": cargo_env unsets RUSTFLAGS in a subshell after folding it
	# into CARGO_TARGET_*_RUSTFLAGS, and unsetting a caller's local only
	# re-exposes the global value, which then overrides the folded flags.
	RUSTFLAGS+=" --remap-path-prefix=${WORKDIR}=/usr/src/debug/${CATEGORY}/${PF}"
	cargo_env meson_src_compile
}

src_test() {
	# meson defines no tests; the Rust unit tests live in the non-gui modules
	local -x ZSTD_SYS_USE_PKG_CONFIG=1
	cargo_src_test
}

pkg_postinst() {
	xdg_pkg_postinst
	gnome2_schemas_update

	elog "Moose is a client: it needs an Ollama server, by default at"
	elog "http://127.0.0.1:11434. Install one locally (sci-ml/ollama or"
	elog "sci-ml/ollama-bin, with whatever GPU backend fits your hardware)"
	elog "or point Moose at a remote instance in its preferences."
	elog "Moose's own \"managed Ollama\" option downloads upstream's prebuilt"
	elog "Ollama binaries at runtime, outside of Portage."
}

pkg_postrm() {
	xdg_pkg_postrm
	gnome2_schemas_update
}
